# Generated by Django 2.1.4 on 2018-12-24 16:46

from django.db import migrations, models
import django.db.models.deletion
import photoslib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photoslib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', photoslib.fields.PhotoField(on_delete=django.db.models.deletion.PROTECT, to='photoslib.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='MultiplyPhotosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', photoslib.fields.ManyPhotosField(to='photoslib.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='SortableMultiplyPhotosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', photoslib.fields.SortableManyPhotosField(help_text=None, to='photoslib.Photo')),
            ],
        ),
    ]
